### ISSUE TITLE
replaceText() on STR in a cell

### ISSUE THREAD

**Issue by NeDetto** [igorrebega/docx-replacer#3]
Hello, i try this lib and it found! :)
but i have this problem: a STR into a table cell in a docx
I launch a script but lib never replace text into cell (as if it did not find the text to be replaced if the text is inside the cell)

Any info about it?

**Comment by igorrebega** [comment]
Hello NeDetto! Let me try to help you here.

Can you provide some example of a file with such cell and code that you are using?

**Comment by NeDetto** [comment]
Hello and thank you very much for answering.
I checked the problem and found that it does not depend on the table cells.
In practice, when I write the name of a variable in the document, if I use
the copy-paste function, the variable is written "bad" and the script does
not recognize it.
That is :)
Watch the example here

[image: error_example.png]


Il giorno mar 4 set 2018 alle ore 09:15 Igor Rebega <
notifications@github.com> ha scritto:

**Comment by igorrebega** [comment]
@NeDetto I can`t see the image from GitHub.

**Comment by NeDetto** [comment]
I'm sorry.
This is the img link

https://ibb.co/nmpXEe

Il giorno mar 4 set 2018 alle ore 10:26 Igor Rebega <
notifications@github.com> ha scritto:

**Comment by igorrebega** [comment]
Okay, I see the problem, docx format is very strange so we can`t be 100% sure that such problems won`t happen, maybe you can try to write your custom script to remove redundant characters?

If no - please provide me an example of such document and I will try to check this on weekend.

**Comment by NeDetto** [comment]
You can find i file here:
https://ufile.io/1ktjn

for now i havn't time to try this mod sory :-/
If i modify your code i send you a message :)

Have a good day :)

Yuri_


Il giorno mar 4 set 2018 alle ore 12:32 Igor Rebega <
notifications@github.com> ha scritto:
